protobuf_sources(
    # name="protos",
    # python_resolve="protobuf",
    # python_resolve="grpc",
    # dependencies=["3rdparty/python#types-protobuf"],
    # python_source_root="src/python",

    grpc=True,
    # python_source_root="src/python",    
)
