python_requirement(
    name="reqs",
    requirements=[
        "grpcio==1.59.0",
        "dependency-injector==4.41.0",
        "protobuf==4.24.4",
        "pyaml-env==1.2.1",
    ],
)
python_sources(
    dependencies=[
        # "src/python/microservices/microservices:reqs",
        "src/python/microservices/microservices/domain",
        "src/python/microservices/microservices/controller",
        # "src/protos/helloworld/v1",
        # "3rdparty/python:grpc#grpcio",
        # "src/python",

        # "src/protos",
    ]
)
