python_requirement(
    name="reqs",
    requirements=[
        "grpcio==1.59.0",
        "dependency-injector==4.41.0",
    ],
)
python_sources(
    dependencies=[
        "src/python/microservices/microservices:reqs",
        "src/python/microservices/microservices/domain",

        # "src/protos",
    ]
)
